### ISSUE TITLE
TypeError: Bot.getGroupMemberInfo is not a function

### ISSUE THREAD

**Issue by Kiana1314** [ldcivan/ddcheck_plugin#3]
0|TRSS-Yunzai  | [TRSSYz][21:21:27.028][ERRO] [DDchecker][cha_chengfen]
0|TRSS-Yunzai  | [TRSSYz][21:21:27.029][ERRO] TypeError: Bot.getGroupMemberInfo is not a function
0|TRSS-Yunzai  |     at example.makeForwardMsg (file:///D:/bot/YZ/Miao-Yunzai/plugins/example/%E6%9F%A5%E6%88%90%E5%88%86.js?1702300791042:301:28)
0|TRSS-Yunzai  |     at example.cha_chengfen (file:///D:/bot/YZ/Miao-Yunzai/plugins/example/%E6%9F%A5%E6%88%90%E5%88%86.js?1702300791042:177:37)
0|TRSS-Yunzai  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
0|TRSS-Yunzai  |     at async PluginsLoader.deal (file:///D:/bot/YZ/Miao-Yunzai/lib/plugins/loader.js:282:52)

**Comment by YujioNako** [comment]
> 0|TRSS-Yunzai | [TRSSYz][21:21:27.028][ERRO] [DDchecker][cha_chengfen]
0|TRSS-Yunzai | [TRSSYz][21:21:27.029][ERRO] TypeError: Bot.getGroupMemberInfo is not a function
0|TRSS-Yunzai | at example.makeForwardMsg (file:///D:/bot/YZ/Miao-Yunzai/plugins/example/%E6%9F%A5%E6%88%90%E5%88%86.js?1702300791042:301:28)
0|TRSS-Yunzai | at example.cha_chengfen (file:///D:/bot/YZ/Miao-Yunzai/plugins/example/%E6%9F%A5%E6%88%90%E5%88%86.js?1702300791042:177:37)
0|TRSS-Yunzai | at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
0|TRSS-Yunzai | at async PluginsLoader.deal (file:///D:/bot/YZ/Miao-Yunzai/lib/plugins/loader.js:282:52)

应该是TRSS-Yunzai的问题，现在尝试修复了，请更新代码后再尝试一次。

若仍有问题请继续联系我；没有问题则请自行关闭issue。

**Comment by Kiana1314** [comment]
刚开始报
0|TRSS-Yunzai  | [TRSSYz][18:38:39.395][ERRO] 发送消息错误：[object Object]
0|TRSS-Yunzai  | [TRSSYz][18:38:39.395][ERRO] [2143298595] message/unsafeSendForward 请求超时, 请检查账号状态或重启QQ！
重启QQNT后
0|TRSS-Yunzai  | [TRSSYz][18:47:12.764][ERRO] 获取群对象失败：找不到群 
0|TRSS-Yunzai  | [TRSSYz][18:47:12.765][ERRO] [DDchecker][cha_chengfen]
0|TRSS-Yunzai  | [TRSSYz][18:47:12.765][ERRO] TypeError: Cannot read properties of undefined (reading 'card')
0|TRSS-Yunzai  |     at example.makeForwardMsg (file:///D:/bot/YZ/Miao-Yunzai/plugins/example/%E6%9F%A5%E6%88%90%E5%88%86.js?1702377699:307:23)
0|TRSS-Yunzai  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
0|TRSS-Yunzai  |     at async example.cha_chengfen (file:///D:/bot/YZ/Miao-Yunzai/plugins/example/%E6%9F%A5%E6%88%90%E5%88%86.js?1702377699:177:26)
0|TRSS-Yunzai  |     at async PluginsLoader.deal (file:///D:/bot/YZ/Miao-Yunzai/lib/plugins/loader.js:282:52)

**Comment by YujioNako** [comment]
> 刚开始报 0|TRSS-Yunzai | [TRSSYz][18:38:39.395][ERRO] 发送消息错误：[object Object] 0|TRSS-Yunzai | [TRSSYz][18:38:39.395][ERRO] [2143298595] message/unsafeSendForward 请求超时, 请检查账号状态或重启QQ！ 重启QQNT后 0|TRSS-Yunzai | [TRSSYz][18:47:12.764][ERRO] 获取群对象失败：找不到群 0|TRSS-Yunzai | [TRSSYz][18:47:12.765][ERRO] [DDchecker][cha_chengfen] 0|TRSS-Yunzai | [TRSSYz][18:47:12.765][ERRO] TypeError: Cannot read properties of undefined (reading 'card') 0|TRSS-Yunzai | at example.makeForwardMsg (file:///D:/bot/YZ/Miao-Yunzai/plugins/example/%E6%9F%A5%E6%88%90%E5%88%86.js?1702377699:307:23) 0|TRSS-Yunzai | at process.processTicksAndRejections (node:internal/process/task_queues:95:5) 0|TRSS-Yunzai | at async example.cha_chengfen (file:///D:/bot/YZ/Miao-Yunzai/plugins/example/%E6%9F%A5%E6%88%90%E5%88%86.js?1702377699:177:26) 0|TRSS-Yunzai | at async PluginsLoader.deal (file:///D:/bot/YZ/Miao-Yunzai/lib/plugins/loader.js:282:52)

可能是TRSS和其他云崽中对nickname的定义不同，请更新代码后再试一次

谢谢您的协助

**Comment by Kiana1314** [comment]
没有报错了  谢谢佬

**Comment by YujioNako** [comment]
不用谢(￣▽￣)


------------------ Original ------------------
From: Kiana1314 ***@***.***&gt;
Date: Wed,Dec 13,2023 1:30 AM
To: ldcivan/ddcheck_plugin ***@***.***&gt;
Cc: Yujio_Nako ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [ldcivan/ddcheck_plugin] TypeError: Bot.getGroupMemberInfo is nota function (Issue #3)





 
没有报错了  谢谢佬
