### ISSUE TITLE
大佬考虑加个切片嘛

### ISSUE THREAD

**Issue by chz091** [ldcivan/ddcheck_plugin#4]
#查成分如果V的列表太长的话会发不出，能否加个切片，目前看到最长的是100条记录，大佬能否加个没100条关注记录一个消息，切片发送

**Comment by YujioNako** [comment]
> #查成分如果V的列表太长的话会发不出，能否加个切片，目前看到最长的是100条记录，大佬能否加个没100条关注记录一个消息，切片发送

请提供一个或多个关注了大量vtb的公开了关注的uid，我这边找不到那么能d的（

**Comment by chz091** [comment]
> uid

#查成分192015206

**Comment by YujioNako** [comment]
> > uid
> 
> 
> 
> #查成分192015206

我这边倒是能发的出来，不过后续还是会尝试切割成多个聊天记录来解决问题，请耐心等候

**Comment by YujioNako** [comment]
初步增加了切割功能，默认开启设置为100，可手动调0关闭

若解决了问题，请自行关闭issue
